import React, { useCallback, useState } from "react";
import { ActivityIndicator, Alert, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Calendar } from "react-native-calendars";
import { SafeAreaView } from "react-native-safe-area-context";
import { useFocusEffect } from "@react-navigation/native";
import { useAuth } from "../context/AuthContext";
import { colors, shadow } from "../theme";
const API_URL=process.env.EXPO_PUBLIC_API_URL||"http://localhost:4000/api"; const today=new Date().toISOString().slice(0,10);
const range=(start,end)=>{const dates=[],cursor=new Date(`${start}T00:00:00Z`),last=new Date(`${end}T00:00:00Z`);while(cursor<=last){dates.push(cursor.toISOString().slice(0,10));cursor.setUTCDate(cursor.getUTCDate()+1);}return dates;};
export default function AvailabilityScreen({navigation}){const{token,pandit}=useAuth();const[dates,setDates]=useState([]);const[start,setStart]=useState(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
const load=useCallback(async()=>{try{setLoading(true);const r=await fetch(`${API_URL}/pandits/${pandit.id}/availability`,{headers:{Authorization:`Bearer ${token}`}}),j=await r.json();if(!r.ok||!j.success)throw new Error(j.message);setDates(j.data||[]);}catch(e){Alert.alert("Unable to load calendar",e.message);}finally{setLoading(false);}},[pandit?.id,token]);useFocusEffect(useCallback(()=>{load();},[load]));
const select=({dateString})=>{if(dates.includes(dateString)){setDates(v=>v.filter(d=>d!==dateString));setStart(null);return;}if(!start){setStart(dateString);return;}const from=start<=dateString?start:dateString,to=start<=dateString?dateString:start;setDates(v=>[...new Set([...v,...range(from,to)])].sort());setStart(null);};
const save=async()=>{try{setSaving(true);const r=await fetch(`${API_URL}/pandits/${pandit.id}/availability`,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({dates})}),j=await r.json();if(!r.ok||!j.success)throw new Error(j.message);Alert.alert("Availability updated",dates.length?`${dates.length} unavailable day${dates.length===1?"":"s"} saved.`:"You are available on all future dates.",[{text:"Done",onPress:()=>navigation.goBack()}]);}catch(e){Alert.alert("Could not save",e.message);}finally{setSaving(false);}};
const marked=dates.reduce((a,d)=>({...a,[d]:{color:"#A23D3D",textColor:"#FFF",startingDay:true,endingDay:true}}),{});if(start)marked[start]={color:"#D49A58",textColor:"#FFF",startingDay:true,endingDay:true};
return <SafeAreaView style={s.screen} edges={["bottom"]}><View style={s.content}><Text style={s.eyebrow}>BOOKING AVAILABILITY</Text><Text style={s.title}>Mark days off</Text><Text style={s.subtitle}>Tap a start date and an end date for multiple days. Tap a red date to make it available again.</Text><View style={s.legend}><View style={s.dot}/><Text style={s.legendText}>{dates.length} unavailable day{dates.length===1?"":"s"}</Text></View><View style={s.card}>{loading?<ActivityIndicator style={{height:330}} color={colors.primary}/>:<Calendar minDate={today} markingType="period" markedDates={marked} onDayPress={select} enableSwipeMonths theme={{todayTextColor:colors.primary,arrowColor:colors.primary,textDayFontWeight:"600",textMonthFontWeight:"800",textMonthFontSize:17}}/>}</View>{start?<Text style={s.hint}>Now select the last day. Select the same day for one day only.</Text>:null}<TouchableOpacity style={[s.button,saving&&s.disabled]} onPress={save} disabled={saving||loading}>{saving?<ActivityIndicator color="#FFF"/>:<Text style={s.buttonText}>Save unavailable dates</Text>}</TouchableOpacity></View></SafeAreaView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},content:{padding:18},eyebrow:{color:colors.primary,fontSize:10,fontWeight:"900",letterSpacing:1.4},title:{color:colors.ink,fontSize:29,fontWeight:"900",marginTop:6},subtitle:{color:colors.muted,fontSize:13,lineHeight:20,marginTop:7},legend:{flexDirection:"row",alignItems:"center",marginTop:18,marginBottom:10},dot:{width:10,height:10,borderRadius:5,backgroundColor:"#A23D3D",marginRight:8},legendText:{color:colors.ink,fontSize:12,fontWeight:"700"},card:{backgroundColor:"#FFF",borderRadius:18,borderWidth:1,borderColor:colors.border,padding:8,...shadow},hint:{color:"#9A642C",fontSize:12,fontWeight:"700",textAlign:"center",marginTop:12},button:{height:54,borderRadius:14,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center",marginTop:20},buttonText:{color:"#FFF",fontSize:15,fontWeight:"900"},disabled:{opacity:.6}});
