import React, { useCallback, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useFocusEffect } from "@react-navigation/native";
import RazorpayCheckout from "react-native-razorpay";
import { useAuth } from "../context/AuthContext";
import { colors, shadow } from "../theme";
const API_URL=process.env.EXPO_PUBLIC_API_URL||"http://localhost:4000/api";

export default function CreditWalletScreen(){const {token,pandit}=useAuth();const [data,setData]=useState({balance:0,packages:[],history:[],credit_price_rupees:10});const [loading,setLoading]=useState(true);const [buying,setBuying]=useState(null);
 const api=async(path,options={})=>{const response=await fetch(`${API_URL}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(options.headers||{})}});const json=await response.json();if(!response.ok||!json.success)throw new Error(json.message||"Request failed");return json;};
 const load=useCallback(async()=>{if(!pandit?.id)return;try{setLoading(true);const result=await api(`/pandits/${pandit.id}/credits`);setData(result.data);}catch(e){Alert.alert("Unable to load credits",e.message);}finally{setLoading(false);}},[pandit?.id,token]);useFocusEffect(useCallback(()=>{load();},[load]));
 const buy=async(pkg)=>{try{setBuying(pkg.credits);const created=await api(`/pandits/${pandit.id}/credits/create-order`,{method:"POST",body:JSON.stringify({credits:pkg.credits})});const order=created.data;let payment;if(order.is_stub)payment={razorpay_order_id:order.order_id,razorpay_payment_id:`pay_stub_${Date.now()}`,razorpay_signature:"stub_signature"};else payment=await RazorpayCheckout.open({key:order.key_id,amount:order.amount,currency:order.currency,order_id:order.order_id,name:"Pandit Credits",description:`Purchase ${pkg.credits} credits`,prefill:{contact:pandit.phone,email:pandit.email||""},theme:{color:colors.primary}});await api(`/pandits/${pandit.id}/credits/verify`,{method:"POST",body:JSON.stringify(payment)});Alert.alert("Purchase successful",`${pkg.credits} credits added to your wallet.`);load();}catch(e){if(e?.code!==2)Alert.alert("Purchase failed",e.description||e.message||"Payment was not completed");}finally{setBuying(null);}};
 return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>CREDIT WALLET</Text><Text style={s.heading}>Service credits</Text><View style={s.hero}><Text style={s.heroLabel}>AVAILABLE CREDITS</Text><Text style={s.balance}>{data.balance}</Text><Text style={s.heroNote}>1 credit = ₹{data.credit_price_rupees} · Credits are debited only when you successfully accept a service.</Text></View><Text style={s.title}>Purchase credits</Text><View style={s.packages}>{(data.packages||[]).map(pkg=><TouchableOpacity key={pkg.credits} disabled={!!buying} onPress={()=>buy(pkg)} style={s.package}><Text style={s.packageCredits}>{pkg.credits}</Text><Text style={s.packageLabel}>credits</Text><Text style={s.packagePrice}>₹{pkg.amount}</Text>{buying===pkg.credits?<ActivityIndicator color={colors.primary}/>:null}</TouchableOpacity>)}</View><Text style={s.title}>Credit history</Text>{loading?<ActivityIndicator color={colors.primary}/>:data.history?.map(item=><View key={item.id} style={s.row}><View style={[s.icon,item.direction==="credit"?s.creditBg:s.debitBg]}><Text style={item.direction==="credit"?s.credit:s.debit}>{item.direction==="credit"?"+":"−"}</Text></View><View style={s.copy}><Text style={s.desc}>{item.pooja_name?`${item.description} · ${item.pooja_name}`:item.description}</Text><Text style={s.date}>{new Date(item.created_at).toLocaleString("en-IN")}</Text></View><Text style={[s.amount,item.direction==="credit"?s.credit:s.debit]}>{item.direction==="credit"?"+":"−"}{item.credits}</Text></View>)}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},content:{padding:18,paddingBottom:35},eyebrow:{color:colors.primary,fontSize:10,fontWeight:"900",letterSpacing:1.3},heading:{fontSize:28,fontWeight:"900",color:colors.ink,marginTop:5},hero:{backgroundColor:"#34251F",borderRadius:20,padding:20,marginTop:15,...shadow},heroLabel:{color:"#D9C9BC",fontSize:9,fontWeight:"900",letterSpacing:1},balance:{color:"#FFD36A",fontSize:48,fontWeight:"900",marginTop:5},heroNote:{color:"#E7DDD5",fontSize:10,lineHeight:16},title:{fontSize:14,fontWeight:"900",color:colors.ink,marginTop:22,marginBottom:10},packages:{flexDirection:"row",flexWrap:"wrap",gap:9},package:{width:"48%",backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:15,padding:14},packageCredits:{fontSize:23,fontWeight:"900",color:colors.primary},packageLabel:{fontSize:9,color:colors.muted},packagePrice:{fontSize:13,fontWeight:"900",color:colors.ink,marginTop:8},row:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:13,padding:11,flexDirection:"row",alignItems:"center",marginBottom:8},icon:{width:34,height:34,borderRadius:10,alignItems:"center",justifyContent:"center"},creditBg:{backgroundColor:colors.greenSoft},debitBg:{backgroundColor:colors.dangerSoft},credit:{color:colors.green},debit:{color:colors.danger},copy:{flex:1,marginLeft:9},desc:{fontSize:10,fontWeight:"800",color:colors.ink},date:{fontSize:8,color:colors.muted,marginTop:4},amount:{fontSize:15,fontWeight:"900"}});
