import { CalendarOutlined, PlusOutlined } from "@ant-design/icons";
import { Button, Card, Col, DatePicker, Form, Input, InputNumber, Modal, Row, Select, Space, Switch, Table, Tag, Typography, message } from "antd";
import dayjs from "dayjs";
import { useEffect, useState } from "react";
import { useAuth } from "../auth/AuthProvider";
import { adminApiRequest } from "../lib/api";

const { Text, Title } = Typography;
export function PricingControlPage(){
 const {token}=useAuth(); const [data,setData]=useState({settings:{},slots:[],rules:[],coupons:[],offers:[],poojas:[]}); const [loading,setLoading]=useState(true); const [modal,setModal]=useState(null); const [editing,setEditing]=useState(null); const [form]=Form.useForm();
 const load=async()=>{try{setLoading(true);const r=await adminApiRequest("/admin/pricing-control",{token});setData(r.data||{});}catch(e){message.error(e.message);}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const open=(type,row=null)=>{setModal(type);setEditing(row);form.resetFields();if(row)form.setFieldsValue({...row,pooja_type_ids:row.poojas?.map(p=>p.id),date_range:row.pricing_date?[dayjs(row.pricing_date),dayjs(row.pricing_end_date||row.pricing_date)]:undefined,starts_at:row.starts_at?dayjs(row.starts_at):undefined,ends_at:row.ends_at?dayjs(row.ends_at):undefined});else if(type==="rule")form.setFieldsValue({payment_percent:30,is_active:true});else if(type==="coupon")form.setFieldsValue({discount_type:"percent",is_active:true});else if(type==="offer")form.setFieldsValue({offer_type:"percent",applies_to_all:true,is_active:true});else form.setFieldsValue({is_active:true});};
 const save=async(v)=>{try{let path,payload={...v};if(modal==="rule"){path="rules";payload.pricing_date=v.date_range[0].format("YYYY-MM-DD");payload.pricing_end_date=v.date_range[1].format("YYYY-MM-DD");delete payload.date_range;}if(modal==="slot")path="slots";if(modal==="coupon"||modal==="offer"){path=modal==="offer"?"offers":"coupons";payload.starts_at=v.starts_at.toISOString();payload.ends_at=v.ends_at.toISOString();}await adminApiRequest(`/admin/pricing-control/${path}${editing?`/${editing.id}`:""}`,{method:editing?"PUT":"POST",token,body:payload});message.success("Saved");setModal(null);load();}catch(e){message.error(e.message);}};
 const toggle=async(type,row)=>{await adminApiRequest(`/admin/pricing-control/${type}/${row.id}`,{method:"PATCH",token,body:{is_active:!row.is_active}});load();};
 const updateDays=async(v)=>{try{await adminApiRequest("/admin/pricing-control/settings",{method:"PUT",token,body:v});message.success("Booking window updated");load();}catch(e){message.error(e.message);}};
 return <Space direction="vertical" size={20} className="page-stack">
  <Card><Title level={3}><CalendarOutlined/> Pricing & Availability Control</Title><Text type="secondary">Control how far customers can book, available arrival slots, festival pricing, payment percentage, and coupons.</Text></Card>
  <Card title="Advance booking window"><Form layout="inline" initialValues={{advance_booking_days:data.settings?.advance_booking_days||30}} key={data.settings?.advance_booking_days} onFinish={updateDays}><Form.Item name="advance_booking_days" label="Customers can book next" rules={[{required:true}]}><InputNumber min={1} max={365} addonAfter="days"/></Form.Item><Button htmlType="submit" type="primary">Save window</Button></Form></Card>
  <Card title="Bookable time slots" extra={<Button icon={<PlusOutlined/>} onClick={()=>open("slot")}>Create slot</Button>}><Table loading={loading} rowKey="id" dataSource={data.slots} pagination={false} columns={[{title:"Label",dataIndex:"label"},{title:"Time",dataIndex:"time_value"},{title:"Status",render:(_,r)=><Tag color={r.is_active?"green":"red"}>{r.is_active?"Open":"Closed"}</Tag>},{title:"Actions",render:(_,r)=><Space><Button onClick={()=>open("slot",r)}>Edit</Button><Button onClick={()=>toggle("slots",r)}>{r.is_active?"Close":"Open"}</Button></Space>}]}/></Card>
  <Card title="Festival/date price calendar" extra={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>open("rule")}>Add date range</Button>}><Table loading={loading} rowKey="id" dataSource={data.rules} columns={[{title:"From",dataIndex:"pricing_date"},{title:"To",dataIndex:"pricing_end_date"},{title:"Festival",dataIndex:"title"},{title:"Pooja",render:(_,r)=>r.pooja_name||"All poojas"},{title:"Selling price",render:(_,r)=>`₹${r.sale_price}`},{title:"List/MRP",render:(_,r)=>r.list_price?`₹${r.list_price}`:"-"},{title:"Pay now",render:(_,r)=>`${r.payment_percent}%`},{title:"Status",render:(_,r)=><Switch checked={r.is_active} onChange={()=>toggle("rules",r)}/>},{title:"",render:(_,r)=><Button onClick={()=>open("rule",r)}>Edit</Button>}]}/></Card>
  <Card title="Discount coupons" extra={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>open("coupon")}>Create coupon</Button>}><Table loading={loading} rowKey="id" dataSource={data.coupons} columns={[{title:"Code",dataIndex:"code",render:v=><Text code strong>{v}</Text>},{title:"Discount",render:(_,r)=>r.discount_type==="percent"?`${r.discount_value}%`:`₹${r.discount_value}`},{title:"Minimum",dataIndex:"min_order_amount"},{title:"Used",render:(_,r)=>`${r.used_count}${r.usage_limit?` / ${r.usage_limit}`:""}`},{title:"Ends",dataIndex:"ends_at",render:v=>dayjs(v).format("DD MMM YYYY")},{title:"Active",render:(_,r)=><Switch checked={r.is_active} onChange={()=>toggle("coupons",r)}/>},{title:"",render:(_,r)=><Button onClick={()=>open("coupon",r)}>Edit</Button>}]}/></Card>
  <Card title="Company-funded 100% payment offers" extra={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>open("offer")}>Create offer</Button>}><Text type="secondary">Customer pays the discounted offer price fully online. Pandit earns 70% of the original applicable service price; your company bears the discount.</Text><Table style={{marginTop:14}} loading={loading} rowKey="id" dataSource={data.offers} columns={[{title:"Offer",render:(_,r)=><><Text strong>{r.title}</Text><br/><Text type="secondary">{r.subtitle}</Text></>},{title:"Customer price",render:(_,r)=>r.offer_type==="percent"?`${r.offer_value}% off`:`Flat ₹${r.offer_value}`},{title:"Services",render:(_,r)=>r.applies_to_all?"All services":r.poojas?.map(p=>p.name).join(", ")},{title:"Window",render:(_,r)=>`${dayjs(r.starts_at).format("DD MMM, HH:mm")} – ${dayjs(r.ends_at).format("DD MMM, HH:mm")}`},{title:"Used",render:(_,r)=>`${r.used_count}${r.usage_limit?` / ${r.usage_limit}`:""}`},{title:"Active",render:(_,r)=><Switch checked={r.is_active} onChange={()=>toggle("offers",r)}/>},{title:"",render:(_,r)=><Button onClick={()=>open("offer",r)}>Edit</Button>}]}/></Card>
  <Modal open={!!modal} onCancel={()=>setModal(null)} onOk={()=>form.submit()} title={`${editing?"Edit":"Create"} ${modal||""}`} width={760}><Form form={form} layout="vertical" onFinish={save}><Row gutter={16}>
   {modal==="slot"&&<><Col span={12}><Form.Item name="label" label="Display label" rules={[{required:true}]}><Input placeholder="07:00 AM"/></Form.Item></Col><Col span={12}><Form.Item name="time_value" label="24-hour time" rules={[{required:true}]}><Input placeholder="07:00"/></Form.Item></Col></>}
   {modal==="rule"&&<><Col span={12}><Form.Item name="date_range" label="Festival From – To" rules={[{required:true}]}><DatePicker.RangePicker style={{width:"100%"}}/></Form.Item></Col><Col span={12}><Form.Item name="title" label="Festival/title" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={12}><Form.Item name="pooja_type_id" label="Apply to"><Select allowClear placeholder="All poojas" options={(data.poojas||[]).map(p=>({value:p.id,label:p.name_en}))}/></Form.Item></Col><Col span={8}><Form.Item name="list_price" label="List price (crossed out)"><InputNumber min={0} style={{width:"100%"}}/></Form.Item></Col><Col span={8}><Form.Item name="sale_price" label="Selling price" rules={[{required:true}]}><InputNumber min={0} style={{width:"100%"}}/></Form.Item></Col><Col span={8}><Form.Item name="payment_percent" label="Pay now"><Select options={[{value:30,label:"30% now"},{value:100,label:"100% full payment"}]}/></Form.Item></Col></>}
   {modal==="coupon"&&<><Col span={8}><Form.Item name="code" label="Coupon code" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={8}><Form.Item name="discount_type" label="Type"><Select options={[{value:"percent",label:"Percentage"},{value:"fixed",label:"Fixed ₹"}]}/></Form.Item></Col><Col span={8}><Form.Item name="discount_value" label="Value" rules={[{required:true}]}><InputNumber min={1} style={{width:"100%"}}/></Form.Item></Col><Col span={8}><Form.Item name="min_order_amount" label="Minimum order"><InputNumber min={0} style={{width:"100%"}}/></Form.Item></Col><Col span={8}><Form.Item name="max_discount_amount" label="Maximum discount"><InputNumber min={0} style={{width:"100%"}}/></Form.Item></Col><Col span={8}><Form.Item name="usage_limit" label="Usage limit"><InputNumber min={1} style={{width:"100%"}}/></Form.Item></Col><Col span={12}><Form.Item name="starts_at" label="Starts" rules={[{required:true}]}><DatePicker showTime style={{width:"100%"}}/></Form.Item></Col><Col span={12}><Form.Item name="ends_at" label="Ends" rules={[{required:true}]}><DatePicker showTime style={{width:"100%"}}/></Form.Item></Col></>}
   {modal==="offer"&&<><Col span={16}><Form.Item name="title" label="Offer title" rules={[{required:true}]}><Input placeholder="Anniversary Maha Offer"/></Form.Item></Col><Col span={8}><Form.Item name="usage_limit" label="Maximum bookings"><InputNumber min={1} style={{width:"100%"}}/></Form.Item></Col><Col span={24}><Form.Item name="subtitle" label="App banner message"><Input placeholder="Celebrate with 40% off on every pooja" maxLength={240}/></Form.Item></Col><Col span={8}><Form.Item name="offer_type" label="Offer type" rules={[{required:true}]}><Select options={[{value:"percent",label:"Percentage off"},{value:"fixed_price",label:"Flat selling price"}]}/></Form.Item></Col><Col span={8}><Form.Item noStyle shouldUpdate>{({getFieldValue})=><Form.Item name="offer_value" label={getFieldValue("offer_type")==="fixed_price"?"Customer pays ₹":"Discount %"} rules={[{required:true}]}><InputNumber min={1} max={getFieldValue("offer_type")==="percent"?100:undefined} style={{width:"100%"}}/></Form.Item>}</Form.Item></Col><Col span={8}><Form.Item name="applies_to_all" label="Apply to all services" valuePropName="checked"><Switch/></Form.Item></Col><Col span={24}><Form.Item noStyle shouldUpdate>{({getFieldValue})=>!getFieldValue("applies_to_all")?<Form.Item name="pooja_type_ids" label="Selected services" rules={[{required:true,message:"Select at least one service"}]}><Select mode="multiple" options={(data.poojas||[]).map(p=>({value:p.id,label:`${p.name_en} (₹${p.base_price})`}))}/></Form.Item>:null}</Form.Item></Col><Col span={12}><Form.Item name="starts_at" label="Offer starts" rules={[{required:true}]}><DatePicker showTime style={{width:"100%"}}/></Form.Item></Col><Col span={12}><Form.Item name="ends_at" label="Offer ends" rules={[{required:true}]}><DatePicker showTime style={{width:"100%"}}/></Form.Item></Col><Col span={24}><Text type="warning">Full online payment is mandatory. Pandit payout remains 70% of the price before this offer.</Text></Col></>}
   <Col span={24}><Form.Item name="is_active" label="Active" valuePropName="checked"><Switch/></Form.Item></Col>
  </Row></Form></Modal>
 </Space>;
}
