const { pool, query } = require("../config/db");
const { createRazorpayOrder, verifyPaymentSignature } = require("../utils/razorpay");
const CREDIT_PRICE = 10;
const PACKAGES = [20,50,100,250];
const own = (req,res) => req.params.id===req.pandit.id || (res.status(403).json({success:false,message:"You can only access your own credit wallet"}),false);

const getCreditWallet=async(req,res,next)=>{try{if(!own(req,res))return;await query("INSERT INTO pandit_credit_wallets(pandit_id) VALUES($1) ON CONFLICT DO NOTHING",[req.pandit.id]);const [wallet,history]=await Promise.all([query("SELECT balance,lifetime_purchased,updated_at FROM pandit_credit_wallets WHERE pandit_id=$1",[req.pandit.id]),query(`SELECT t.id,t.booking_id,t.type,t.direction,t.credits,t.rupee_amount,t.description,t.created_at,pt.name_en AS pooja_name FROM pandit_credit_transactions t LEFT JOIN bookings b ON b.id=t.booking_id LEFT JOIN pooja_types pt ON pt.id=b.pooja_type_id WHERE t.pandit_id=$1 ORDER BY t.created_at DESC LIMIT 100`,[req.pandit.id])]);res.json({success:true,data:{...wallet.rows[0],credit_price_rupees:CREDIT_PRICE,packages:PACKAGES.map(credits=>({credits,amount:credits*CREDIT_PRICE})),history:history.rows}});}catch(e){next(e);}};
const createCreditOrder=async(req,res,next)=>{try{if(!own(req,res))return;const credits=Number(req.body.credits);if(!PACKAGES.includes(credits))return res.status(400).json({success:false,message:"Select a valid credit package"});const amount=credits*CREDIT_PRICE;const order=await createRazorpayOrder({amount,receipt:`credit_${req.pandit.id.slice(0,8)}_${Date.now()}`,notes:{type:"pandit_credits",pandit_id:req.pandit.id,credits:String(credits)}});await query("INSERT INTO pandit_credit_purchase_orders(pandit_id,credits,amount,razorpay_order_id) VALUES($1,$2,$3,$4)",[req.pandit.id,credits,amount,order.id]);res.status(201).json({success:true,data:{order_id:order.id,amount:order.amount,currency:order.currency,key_id:process.env.RAZORPAY_KEY_ID,credits,is_stub:order.is_stub}});}catch(e){next(e);}};
const verifyCreditPurchase=async(req,res,next)=>{const client=await pool.connect();try{if(!own(req,res))return;const {razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body;if(!verifyPaymentSignature({orderId:razorpay_order_id,paymentId:razorpay_payment_id,signature:razorpay_signature}))return res.status(400).json({success:false,message:"Invalid payment signature"});await client.query("BEGIN");const order=await client.query("SELECT * FROM pandit_credit_purchase_orders WHERE razorpay_order_id=$1 AND pandit_id=$2 FOR UPDATE",[razorpay_order_id,req.pandit.id]);if(!order.rowCount){await client.query("ROLLBACK");return res.status(404).json({success:false,message:"Credit order not found"});}if(order.rows[0].status==='paid'){await client.query("ROLLBACK");return res.json({success:true,message:"Credits already added"});}await client.query("INSERT INTO pandit_credit_wallets(pandit_id) VALUES($1) ON CONFLICT DO NOTHING",[req.pandit.id]);await client.query("UPDATE pandit_credit_wallets SET balance=balance+$1,lifetime_purchased=lifetime_purchased+$1,updated_at=NOW() WHERE pandit_id=$2",[order.rows[0].credits,req.pandit.id]);await client.query("INSERT INTO pandit_credit_transactions(pandit_id,type,direction,credits,rupee_amount,description,razorpay_order_id,razorpay_payment_id) VALUES($1,'purchase','credit',$2,$3,'Credit package purchased',$4,$5)",[req.pandit.id,order.rows[0].credits,order.rows[0].amount,razorpay_order_id,razorpay_payment_id]);await client.query("UPDATE pandit_credit_purchase_orders SET status='paid',paid_at=NOW() WHERE id=$1",[order.rows[0].id]);await client.query("COMMIT");res.json({success:true,message:`${order.rows[0].credits} credits added`});}catch(e){try{await client.query("ROLLBACK");}catch{}if(e.code==='23505')return res.json({success:true,message:"Credits already added"});next(e);}finally{client.release();}};
const creditCapturedOrder=async(client,orderId,paymentId)=>{const result=await client.query("SELECT * FROM pandit_credit_purchase_orders WHERE razorpay_order_id=$1 FOR UPDATE",[orderId]);if(!result.rowCount)return false;const order=result.rows[0];if(order.status==='paid')return true;await client.query("INSERT INTO pandit_credit_wallets(pandit_id) VALUES($1) ON CONFLICT DO NOTHING",[order.pandit_id]);await client.query("UPDATE pandit_credit_wallets SET balance=balance+$1,lifetime_purchased=lifetime_purchased+$1,updated_at=NOW() WHERE pandit_id=$2",[order.credits,order.pandit_id]);await client.query("INSERT INTO pandit_credit_transactions(pandit_id,type,direction,credits,rupee_amount,description,razorpay_order_id,razorpay_payment_id) VALUES($1,'purchase','credit',$2,$3,'Credit package purchased',$4,$5) ON CONFLICT DO NOTHING",[order.pandit_id,order.credits,order.amount,orderId,paymentId]);await client.query("UPDATE pandit_credit_purchase_orders SET status='paid',paid_at=NOW() WHERE id=$1",[order.id]);return true;};
module.exports={getCreditWallet,createCreditOrder,verifyCreditPurchase,creditCapturedOrder};
