const { pool, query } = require("../config/db");

const getPricingControl = async (_req, res, next) => { try {
  const [settings, slots, rules, creditRules, coupons, offers, poojas] = await Promise.all([
    query("SELECT * FROM marketplace_settings WHERE id=1"),
    query("SELECT id,label,to_char(time_value,'HH24:MI') AS time_value,is_active FROM booking_time_slots ORDER BY time_value"),
    query("SELECT r.*, p.name_en AS pooja_name FROM date_pricing_rules r LEFT JOIN pooja_types p ON p.id=r.pooja_type_id ORDER BY pricing_date DESC"),
    query("SELECT r.*,p.name_en AS pooja_name FROM date_credit_rules r LEFT JOIN pooja_types p ON p.id=r.pooja_type_id ORDER BY credit_date DESC"),
    query("SELECT * FROM coupons ORDER BY created_at DESC"),
    query(`SELECT o.*,COALESCE(json_agg(json_build_object('id',p.id,'name',p.name_en)) FILTER (WHERE p.id IS NOT NULL),'[]') AS poojas
      FROM promotional_offers o LEFT JOIN promotional_offer_poojas op ON op.offer_id=o.id LEFT JOIN pooja_types p ON p.id=op.pooja_type_id
      GROUP BY o.id ORDER BY o.created_at DESC`),
    query("SELECT id,name_en,base_price FROM pooja_types WHERE is_active=TRUE ORDER BY name_en"),
  ]);
  res.json({success:true,data:{settings:settings.rows[0],slots:slots.rows,rules:rules.rows,creditRules:creditRules.rows,coupons:coupons.rows,offers:offers.rows,poojas:poojas.rows}});
} catch(e){next(e);} };

const updateSettings = async (req,res,next) => { try { const days=Number(req.body.advance_booking_days); if(!Number.isInteger(days)||days<1||days>365)return res.status(400).json({success:false,message:"Advance days must be 1-365"}); const r=await query("UPDATE marketplace_settings SET advance_booking_days=$1,updated_at=NOW() WHERE id=1 RETURNING *",[days]);res.json({success:true,data:r.rows[0]}); }catch(e){next(e);} };
const saveSlot = async (req,res,next) => { try { const {label,time_value,is_active=true}=req.body;if(!label||!/^\d{2}:\d{2}$/.test(time_value||""))return res.status(400).json({success:false,message:"Label and HH:MM time are required"});const r=req.params.id?await query("UPDATE booking_time_slots SET label=$1,time_value=$2,is_active=$3,updated_at=NOW() WHERE id=$4 RETURNING *",[label,time_value,is_active,req.params.id]):await query("INSERT INTO booking_time_slots(label,time_value,is_active) VALUES($1,$2,$3) RETURNING *",[label,time_value,is_active]);res.json({success:true,data:r.rows[0]});}catch(e){next(e);} };
const saveRule = async (req,res,next) => { try {const {pricing_date,pricing_end_date,pooja_type_id,title,sale_price,list_price,payment_percent=30,is_active=true}=req.body;const endDate=pricing_end_date||pricing_date;if(!pricing_date||!endDate||endDate<pricing_date||!title||Number(sale_price)<0||![30,100].includes(Number(payment_percent)))return res.status(400).json({success:false,message:"Valid From/To dates, title, price and payment policy are required"});const params=[pricing_date,endDate,pooja_type_id||null,title,Number(sale_price),list_price==null?null:Number(list_price),Number(payment_percent),is_active];let r;if(req.params.id)r=await query("UPDATE date_pricing_rules SET pricing_date=$1,pricing_end_date=$2,pooja_type_id=$3,title=$4,sale_price=$5,list_price=$6,payment_percent=$7,is_active=$8,updated_at=NOW() WHERE id=$9 RETURNING *",[...params,req.params.id]);else r=await query("INSERT INTO date_pricing_rules(pricing_date,pricing_end_date,pooja_type_id,title,sale_price,list_price,payment_percent,is_active) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",params);res.json({success:true,data:r.rows[0]});}catch(e){next(e);} };
const saveCoupon = async (req,res,next) => { try {const b=req.body;const params=[String(b.code||"").trim().toUpperCase(),b.discount_type,Number(b.discount_value),Number(b.min_order_amount||0),b.max_discount_amount==null?null:Number(b.max_discount_amount),b.starts_at,b.ends_at,b.usage_limit==null?null:Number(b.usage_limit),b.is_active!==false];if(!params[0]||!["percent","fixed"].includes(params[1])||params[2]<=0||!params[5]||!params[6])return res.status(400).json({success:false,message:"Complete valid coupon details are required"});let r;if(req.params.id)r=await query("UPDATE coupons SET code=$1,discount_type=$2,discount_value=$3,min_order_amount=$4,max_discount_amount=$5,starts_at=$6,ends_at=$7,usage_limit=$8,is_active=$9,updated_at=NOW() WHERE id=$10 RETURNING *",[...params,req.params.id]);else r=await query("INSERT INTO coupons(code,discount_type,discount_value,min_order_amount,max_discount_amount,starts_at,ends_at,usage_limit,is_active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",params);res.json({success:true,data:r.rows[0]});}catch(e){next(e);} };
const saveOffer = async (req,res,next) => { const client=await pool.connect();try{const b=req.body;const all=b.applies_to_all!==false;const ids=all?[]:[...new Set(Array.isArray(b.pooja_type_ids)?b.pooja_type_ids:[])];const value=Number(b.offer_value);if(!b.title||!["percent","fixed_price"].includes(b.offer_type)||value<=0||(b.offer_type==="percent"&&value>100)||!b.starts_at||!b.ends_at||new Date(b.ends_at)<=new Date(b.starts_at)||(!all&&!ids.length))return res.status(400).json({success:false,message:"Complete valid offer details and at least one service are required"});await client.query("BEGIN");const conflict=await client.query(`SELECT DISTINCT o.title FROM promotional_offers o LEFT JOIN promotional_offer_poojas op ON op.offer_id=o.id WHERE o.is_active=TRUE AND o.id<>COALESCE($1::uuid,'00000000-0000-0000-0000-000000000000') AND tstzrange(o.starts_at,o.ends_at,'[]') && tstzrange($2::timestamptz,$3::timestamptz,'[]') AND (o.applies_to_all=TRUE OR $4::boolean=TRUE OR op.pooja_type_id=ANY($5::uuid[])) LIMIT 1`,[req.params.id||null,b.starts_at,b.ends_at,all,ids]);if(conflict.rowCount){await client.query("ROLLBACK");return res.status(409).json({success:false,message:`Offer overlaps with active offer: ${conflict.rows[0].title}`});}const params=[b.title,String(b.subtitle||"").trim()||null,b.offer_type,value,all,b.starts_at,b.ends_at,b.usage_limit==null?null:Number(b.usage_limit),b.is_active!==false];const result=req.params.id?await client.query("UPDATE promotional_offers SET title=$1,subtitle=$2,offer_type=$3,offer_value=$4,applies_to_all=$5,starts_at=$6,ends_at=$7,usage_limit=$8,is_active=$9,updated_at=NOW() WHERE id=$10 RETURNING *",[...params,req.params.id]):await client.query("INSERT INTO promotional_offers(title,subtitle,offer_type,offer_value,applies_to_all,starts_at,ends_at,usage_limit,is_active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",params);if(!result.rowCount)throw Object.assign(new Error("Offer not found"),{status:404});await client.query("DELETE FROM promotional_offer_poojas WHERE offer_id=$1",[result.rows[0].id]);for(const id of ids)await client.query("INSERT INTO promotional_offer_poojas(offer_id,pooja_type_id) VALUES($1,$2)",[result.rows[0].id,id]);await client.query("COMMIT");res.json({success:true,data:result.rows[0]});}catch(e){try{await client.query("ROLLBACK");}catch{}if(e.status)return res.status(e.status).json({success:false,message:e.message});next(e);}finally{client.release();}};
const saveCreditRule=async(req,res,next)=>{try{const b=req.body;const start=b.credit_date,end=b.credit_end_date||start,cost=Number(b.credit_cost),pooja=b.pooja_type_id||null;if(!start||!end||end<start||!b.title||!Number.isInteger(cost)||cost<1)return res.status(400).json({success:false,message:"Valid date range, title and credit cost are required"});const conflict=await query(`SELECT title FROM date_credit_rules WHERE is_active=TRUE AND id<>COALESCE($1::uuid,'00000000-0000-0000-0000-000000000000') AND daterange(credit_date,credit_end_date,'[]') && daterange($2::date,$3::date,'[]') AND (pooja_type_id IS NULL OR $4::uuid IS NULL OR pooja_type_id=$4) LIMIT 1`,[req.params.id||null,start,end,pooja]);if(conflict.rowCount)return res.status(409).json({success:false,message:`Credit rule overlaps with: ${conflict.rows[0].title}`});const params=[start,end,pooja,b.title,cost,b.is_active!==false];const result=req.params.id?await query("UPDATE date_credit_rules SET credit_date=$1,credit_end_date=$2,pooja_type_id=$3,title=$4,credit_cost=$5,is_active=$6,updated_at=NOW() WHERE id=$7 RETURNING *",[...params,req.params.id]):await query("INSERT INTO date_credit_rules(credit_date,credit_end_date,pooja_type_id,title,credit_cost,is_active) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",params);res.json({success:true,data:result.rows[0]});}catch(e){next(e);}};
const toggleRecord = (table) => async(req,res,next)=>{try{const r=await query(`UPDATE ${table} SET is_active=$1,updated_at=NOW() WHERE id=$2 RETURNING *`,[Boolean(req.body.is_active),req.params.id]);res.json({success:true,data:r.rows[0]});}catch(e){next(e);}};
module.exports={getPricingControl,updateSettings,saveSlot,saveRule,saveCreditRule,saveCoupon,saveOffer,toggleSlot:toggleRecord("booking_time_slots"),toggleRule:toggleRecord("date_pricing_rules"),toggleCreditRule:toggleRecord("date_credit_rules"),toggleCoupon:toggleRecord("coupons"),toggleOffer:toggleRecord("promotional_offers")};
