const { query } = require("../config/db");

const getPricingControl = async (_req, res, next) => { try {
  const [settings, slots, rules, coupons, poojas] = await Promise.all([
    query("SELECT * FROM marketplace_settings WHERE id=1"),
    query("SELECT id,label,to_char(time_value,'HH24:MI') AS time_value,is_active FROM booking_time_slots ORDER BY time_value"),
    query("SELECT r.*, p.name_en AS pooja_name FROM date_pricing_rules r LEFT JOIN pooja_types p ON p.id=r.pooja_type_id ORDER BY pricing_date DESC"),
    query("SELECT * FROM coupons ORDER BY created_at DESC"),
    query("SELECT id,name_en,base_price FROM pooja_types WHERE is_active=TRUE ORDER BY name_en"),
  ]);
  res.json({success:true,data:{settings:settings.rows[0],slots:slots.rows,rules:rules.rows,coupons:coupons.rows,poojas:poojas.rows}});
} catch(e){next(e);} };

const updateSettings = async (req,res,next) => { try { const days=Number(req.body.advance_booking_days); if(!Number.isInteger(days)||days<1||days>365)return res.status(400).json({success:false,message:"Advance days must be 1-365"}); const r=await query("UPDATE marketplace_settings SET advance_booking_days=$1,updated_at=NOW() WHERE id=1 RETURNING *",[days]);res.json({success:true,data:r.rows[0]}); }catch(e){next(e);} };
const saveSlot = async (req,res,next) => { try { const {label,time_value,is_active=true}=req.body;if(!label||!/^\d{2}:\d{2}$/.test(time_value||""))return res.status(400).json({success:false,message:"Label and HH:MM time are required"});const r=req.params.id?await query("UPDATE booking_time_slots SET label=$1,time_value=$2,is_active=$3,updated_at=NOW() WHERE id=$4 RETURNING *",[label,time_value,is_active,req.params.id]):await query("INSERT INTO booking_time_slots(label,time_value,is_active) VALUES($1,$2,$3) RETURNING *",[label,time_value,is_active]);res.json({success:true,data:r.rows[0]});}catch(e){next(e);} };
const saveRule = async (req,res,next) => { try {const {pricing_date,pricing_end_date,pooja_type_id,title,sale_price,list_price,payment_percent=30,is_active=true}=req.body;const endDate=pricing_end_date||pricing_date;if(!pricing_date||!endDate||endDate<pricing_date||!title||Number(sale_price)<0||![30,100].includes(Number(payment_percent)))return res.status(400).json({success:false,message:"Valid From/To dates, title, price and payment policy are required"});const params=[pricing_date,endDate,pooja_type_id||null,title,Number(sale_price),list_price==null?null:Number(list_price),Number(payment_percent),is_active];let r;if(req.params.id)r=await query("UPDATE date_pricing_rules SET pricing_date=$1,pricing_end_date=$2,pooja_type_id=$3,title=$4,sale_price=$5,list_price=$6,payment_percent=$7,is_active=$8,updated_at=NOW() WHERE id=$9 RETURNING *",[...params,req.params.id]);else r=await query("INSERT INTO date_pricing_rules(pricing_date,pricing_end_date,pooja_type_id,title,sale_price,list_price,payment_percent,is_active) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",params);res.json({success:true,data:r.rows[0]});}catch(e){next(e);} };
const saveCoupon = async (req,res,next) => { try {const b=req.body;const params=[String(b.code||"").trim().toUpperCase(),b.discount_type,Number(b.discount_value),Number(b.min_order_amount||0),b.max_discount_amount==null?null:Number(b.max_discount_amount),b.starts_at,b.ends_at,b.usage_limit==null?null:Number(b.usage_limit),b.is_active!==false];if(!params[0]||!["percent","fixed"].includes(params[1])||params[2]<=0||!params[5]||!params[6])return res.status(400).json({success:false,message:"Complete valid coupon details are required"});let r;if(req.params.id)r=await query("UPDATE coupons SET code=$1,discount_type=$2,discount_value=$3,min_order_amount=$4,max_discount_amount=$5,starts_at=$6,ends_at=$7,usage_limit=$8,is_active=$9,updated_at=NOW() WHERE id=$10 RETURNING *",[...params,req.params.id]);else r=await query("INSERT INTO coupons(code,discount_type,discount_value,min_order_amount,max_discount_amount,starts_at,ends_at,usage_limit,is_active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",params);res.json({success:true,data:r.rows[0]});}catch(e){next(e);} };
const toggleRecord = (table) => async(req,res,next)=>{try{const r=await query(`UPDATE ${table} SET is_active=$1,updated_at=NOW() WHERE id=$2 RETURNING *`,[Boolean(req.body.is_active),req.params.id]);res.json({success:true,data:r.rows[0]});}catch(e){next(e);}};
module.exports={getPricingControl,updateSettings,saveSlot,saveRule,saveCoupon,toggleSlot:toggleRecord("booking_time_slots"),toggleRule:toggleRecord("date_pricing_rules"),toggleCoupon:toggleRecord("coupons")};
