import React, { useState } from "react";
import { StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { colors } from "../../theme/homeTheme";

export default function HomeHeader({ name, location, notificationCount, onSearch, onLanguage, onBookings }) {
  const [query, setQuery] = useState("");
  const submit = () => onSearch(query.trim());
  return <><View style={s.header}><View style={s.avatar}><Text style={s.initial}>{name.charAt(0).toUpperCase()}</Text></View><View style={s.copy}><Text style={s.greeting}>Welcome, <Text style={s.name}>{name}</Text></Text><Text numberOfLines={1} style={s.location}>● {location}</Text></View><TouchableOpacity accessibilityLabel="Change language" style={s.language} onPress={onLanguage}><Text style={s.languageText}>EN | हिं</Text></TouchableOpacity><TouchableOpacity accessibilityLabel="Open booking notifications" style={s.bell} onPress={onBookings}><Text style={s.bellText}>♟</Text>{notificationCount > 0 && <Text style={s.badge}>{notificationCount > 9 ? "9+" : notificationCount}</Text>}</TouchableOpacity></View><View style={s.search}><Text style={s.searchIcon}>⌕</Text><TextInput style={s.input} value={query} onChangeText={setQuery} onSubmitEditing={submit} returnKeyType="search" placeholder="Search poojas or pandits" placeholderTextColor={colors.muted} /><TouchableOpacity accessibilityLabel="Search" style={s.searchButton} onPress={submit}><Text style={s.searchButtonText}>›</Text></TouchableOpacity></View></>;
}

const s = StyleSheet.create({ header: { height: 61, flexDirection: "row", alignItems: "center" }, avatar: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#E8C24F", alignItems: "center", justifyContent: "center" }, initial: { color: colors.primary, fontWeight: "800", fontSize: 17 }, copy: { flex: 1, marginLeft: 10 }, greeting: { color: colors.muted, fontSize: 12 }, name: { color: colors.ink, fontWeight: "700" }, location: { color: colors.muted, fontSize: 11, marginTop: 5 }, language: { borderWidth: 1, borderColor: colors.border, borderRadius: 18, paddingHorizontal: 10, paddingVertical: 8 }, languageText: { color: colors.ink, fontSize: 10, fontWeight: "600" }, bell: { width: 34, height: 34, alignItems: "center", justifyContent: "center", marginLeft: 5 }, bellText: { color: colors.primary, fontSize: 20 }, badge: { position: "absolute", top: 0, right: 0, backgroundColor: colors.primary, color: "white", borderRadius: 8, minWidth: 16, height: 16, paddingHorizontal: 3, textAlign: "center", fontSize: 9, fontWeight: "800" }, search: { height: 44, flexDirection: "row", alignItems: "center", backgroundColor: "#F7F3ED", borderRadius: 10, paddingLeft: 13, marginBottom: 17 }, searchIcon: { color: colors.muted, fontSize: 23 }, input: { flex: 1, color: colors.ink, fontSize: 12, marginLeft: 9, height: 44 }, searchButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: "white", alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border }, searchButtonText: { color: colors.primary, fontSize: 28 } });
