import React from "react";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import SectionTitle from "./SectionTitle";
import { colors, shadow } from "../../theme/homeTheme";

export default function NearbyPandits({ pandits, onBook, onView, onViewAll }) {
  const items = pandits.slice(0, 3);
  return <View style={s.section}><SectionTitle title="Popular Near You" hindi="आपके पास के पंडित" onViewAll={onViewAll} />{items.length ? items.map((pandit) => <View style={s.card} key={pandit.id}><View style={s.top}><View style={s.avatar}><Text style={s.om}>ॐ</Text>{pandit.is_verified && <Text style={s.tick}>✓</Text>}</View><View style={s.info}><Text style={s.name}>{pandit.name}</Text>{pandit.rating != null && <Text style={s.rating}>★ {pandit.rating} <Text style={s.reviews}>({pandit.total_ratings_count || 0} reviews)</Text></Text>}{pandit.experience_years != null && <Text style={s.meta}>{pandit.experience_years} years experience</Text>}</View></View>{pandit.specializations?.length ? <Text numberOfLines={1} style={s.spec}>{pandit.specializations.join(" · ")}</Text> : null}<View style={s.actions}><TouchableOpacity style={s.outline} onPress={() => onView(pandit)}><Text style={s.outlineText}>View Profile</Text></TouchableOpacity><TouchableOpacity style={s.book} onPress={() => onBook(pandit)}><Text style={s.bookText}>Book Now</Text></TouchableOpacity></View></View>) : <Text style={s.empty}>No nearby pandits available right now.</Text>}</View>;
}
const s = StyleSheet.create({ section: { marginBottom: 21 }, card: { backgroundColor: "white", borderWidth: 1, borderColor: colors.border, borderRadius: 15, padding: 12, marginBottom: 10, ...shadow }, top: { flexDirection: "row", alignItems: "center" }, avatar: { width: 46, height: 46, borderRadius: 23, backgroundColor: "#F4EEE3", alignItems: "center", justifyContent: "center" }, om: { color: colors.gold, fontSize: 20 }, tick: { position: "absolute", right: -2, bottom: -1, width: 16, height: 16, borderRadius: 8, backgroundColor: colors.green, color: "white", textAlign: "center", fontSize: 10 }, info: { flex: 1, marginLeft: 10 }, name: { color: colors.ink, fontSize: 13, fontWeight: "700" }, rating: { color: colors.gold, fontSize: 10, fontWeight: "700", marginTop: 3 }, reviews: { color: colors.muted, fontWeight: "400" }, meta: { color: colors.muted, fontSize: 9, marginTop: 3 }, spec: { color: colors.primary, fontSize: 10, marginTop: 9 }, actions: { flexDirection: "row", gap: 8, marginTop: 11 }, outline: { flex: 1, height: 33, borderWidth: 1, borderColor: "#DCCFC2", borderRadius: 17, alignItems: "center", justifyContent: "center" }, outlineText: { color: colors.muted, fontSize: 10, fontWeight: "600" }, book: { flex: 1, height: 33, borderRadius: 17, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }, bookText: { color: "white", fontSize: 10, fontWeight: "700" }, empty: { color: colors.muted, fontSize: 12 } });
