import React from "react";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import SectionTitle from "./SectionTitle";
import { colors, shadow } from "../../theme/homeTheme";

export default function UpcomingCeremony({ booking, onPress }) {
  if (!booking) return null;
  const date = new Date(booking.booking_date).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  return <View style={s.section}><SectionTitle title="Upcoming Ceremony" hindi="आगामी अनुष्ठान" /><View style={s.card}><View style={s.top}><View style={s.icon}><Text style={s.spark}>✦</Text></View><View style={s.copy}><Text style={s.title}>{booking.name_en || booking.name}</Text>{booking.name_hi ? <Text style={s.hindi}>{booking.name_hi}</Text> : null}</View><Text style={s.status}>{booking.status}</Text></View><View style={s.rule} /><Text style={s.meta}>▣ {date}   ◷ {booking.booking_time}</Text>{booking.address ? <Text numberOfLines={1} style={s.meta}>{booking.address}</Text> : null}<View style={s.bottom}>{booking.confirmed_pandit?.name ? <Text style={s.pandit}>{booking.confirmed_pandit.name}</Text> : <View />}<TouchableOpacity style={s.details} onPress={onPress}><Text style={s.detailsText}>View Details</Text></TouchableOpacity></View></View></View>;
}
const s = StyleSheet.create({ section: { marginBottom: 24 }, card: { backgroundColor: "white", borderRadius: 15, borderWidth: 1, borderColor: colors.border, padding: 13, ...shadow }, top: { flexDirection: "row", alignItems: "center" }, icon: { width: 42, height: 42, borderRadius: 12, backgroundColor: colors.soft, alignItems: "center", justifyContent: "center" }, spark: { color: colors.gold, fontSize: 20 }, copy: { flex: 1, marginLeft: 10 }, title: { color: colors.ink, fontWeight: "700", fontSize: 13 }, hindi: { color: colors.muted, fontSize: 9, marginTop: 3 }, status: { color: colors.green, fontSize: 10, fontWeight: "700", textTransform: "capitalize" }, rule: { height: 1, backgroundColor: colors.border, marginVertical: 11 }, meta: { color: colors.muted, fontSize: 10, marginBottom: 5 }, bottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 5 }, pandit: { color: colors.ink, fontSize: 11, fontWeight: "600" }, details: { backgroundColor: colors.primary, borderRadius: 14, paddingHorizontal: 12, paddingVertical: 7 }, detailsText: { color: "white", fontSize: 9, fontWeight: "700" } });
