import React, { useCallback, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Switch, Text, TouchableOpacity, View } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useTranslation } from "react-i18next";
import useLiveRefresh from "../hooks/useLiveRefresh";

const API_URL = process.env.EXPO_PUBLIC_API_URL || "http://localhost:4000/api";

const Row = ({ icon, title, subtitle, onPress, right, danger }) => <TouchableOpacity style={s.row} onPress={onPress} disabled={!onPress}><View style={[s.rowIcon, danger && s.dangerIcon]}><Text style={[s.iconText, danger && s.danger]}>{icon}</Text></View><View style={s.rowCopy}><Text style={[s.rowTitle, danger && s.danger]}>{title}</Text>{subtitle ? <Text style={s.rowSubtitle}>{subtitle}</Text> : null}</View>{right || (onPress ? <Text style={s.chevron}>›</Text> : null)}</TouchableOpacity>;
const Section = ({ title, children }) => <View><Text style={s.sectionTitle}>{title}</Text><View style={s.section}>{children}</View></View>;

export default function ProfileScreen({ navigation }) {
  const insets = useSafeAreaInsets();
  const { i18n } = useTranslation();
  const [user, setUser] = useState(null);
  const [bookings, setBookings] = useState([]);
  const [notifications, setNotifications] = useState(true);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    try {
      const [token, userId, storedNotifications] = await Promise.all([AsyncStorage.getItem("user-app-token"), AsyncStorage.getItem("user-id"), AsyncStorage.getItem("user-notifications-enabled")]);
      if (!token || !userId) return;
      if (storedNotifications != null) setNotifications(storedNotifications === "true");
      const [profileResponse, bookingsResponse] = await Promise.all([fetch(`${API_URL}/auth/me`, { headers: { Authorization: `Bearer ${token}` } }), fetch(`${API_URL}/bookings/user/${userId}?limit=100`, { headers: { Authorization: `Bearer ${token}` } })]);
      const [profile, bookingData] = await Promise.all([profileResponse.json(), bookingsResponse.json()]);
      if (profileResponse.ok && profile.success) setUser(profile.user);
      if (bookingsResponse.ok && bookingData.success) setBookings(bookingData.data || []);
    } finally { setLoading(false); }
  }, []);
  useLiveRefresh(load);

  const toggleNotifications = async (value) => { setNotifications(value); await AsyncStorage.setItem("user-notifications-enabled", String(value)); };
  const open = (type, title) => navigation.navigate("AccountDetail", { type, title, user });
  const logout = async () => { await AsyncStorage.multiRemove(["user-app-token", "user-id"]); navigation.reset({ index: 0, routes: [{ name: "Onboarding" }] }); };
  const deleteAccount = () => Alert.alert("Delete account?", "This permanently removes your account, bookings and payment records.", [{ text: "Keep Account", style: "cancel" }, { text: "Delete", style: "destructive", onPress: async () => { try { const token = await AsyncStorage.getItem("user-app-token"); const response = await fetch(`${API_URL}/auth/me`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); const json = await response.json(); if (!response.ok || !json.success) throw new Error(json.message); await logout(); } catch (error) { Alert.alert("Delete failed", error.message || "Please try again."); } } }]);

  const completed = bookings.filter((item) => item.status === "completed").length;
  const addressCount = user?.address ? 1 : 0;
  const name = user?.name || "Account";
  if (loading && !user) return <View style={s.center}><ActivityIndicator color="#913B3B" /></View>;

  return <ScrollView style={s.screen} contentContainerStyle={{ paddingTop: insets.top + 14, paddingBottom: 30 }}><View style={s.header}><View><Text style={s.heading}>My Account</Text><Text style={s.headingHindi}>मेरा खाता</Text></View><TouchableOpacity style={s.bell} onPress={() => navigation.navigate("BookingsTab")}><Text style={s.bellText}>♧</Text></TouchableOpacity></View><View style={s.profileCard}><View style={s.avatar}><Text style={s.avatarText}>{name.charAt(0).toUpperCase()}</Text><View style={s.editDot}><Text style={s.editText}>✎</Text></View></View><View style={s.profileCopy}><Text style={s.name}>{name}</Text>{user?.phone ? <Text style={s.profileMeta}>+91 {String(user.phone).slice(-10)}</Text> : null}{user?.email ? <Text style={s.profileMeta}>{user.email}</Text> : null}</View><Text style={s.verified}>Verified</Text></View><View style={s.stats}><View style={s.stat}><Text style={s.statNumber}>{bookings.length}</Text><Text style={s.statLabel}>Bookings</Text></View><View style={s.stat}><Text style={s.statNumber}>{completed}</Text><Text style={s.statLabel}>Completed</Text></View><View style={s.stat}><Text style={s.statNumber}>{addressCount}</Text><Text style={s.statLabel}>Addresses</Text></View></View><Section title="Preferences · प्राथमिकताएं"><Row icon="◉" title="Language" subtitle={i18n.language === "hi" ? "हिन्दी" : "English"} right={<TouchableOpacity onPress={() => i18n.changeLanguage(i18n.language === "hi" ? "en" : "hi")}><Text style={s.rightText}>{i18n.language === "hi" ? "हिन्दी" : "English"}  ›</Text></TouchableOpacity>} /><Row icon="♧" title="Notifications" subtitle={notifications ? "Enabled" : "Disabled"} right={<Switch value={notifications} onValueChange={toggleNotifications} trackColor={{ false: "#DDD4CC", true: "#C69595" }} thumbColor={notifications ? "#913B3B" : "#F6F2EE"} />} /></Section><Section title="Account · खाता"><Row icon="♙" title="Edit Profile" subtitle="Update your name and email" onPress={() => open("edit", "Edit Profile")} /><Row icon="⌖" title="Saved Addresses" subtitle={`${addressCount} address${addressCount === 1 ? "" : "es"} saved`} onPress={() => open("addresses", "Saved Addresses")} /><Row icon="▣" title="Payment History" subtitle="View past transactions" onPress={() => open("payments", "Payment History")} /></Section><Section title="Support · सहायता"><Row icon="?" title="Help & Support" subtitle="FAQs, chat and call support" onPress={() => open("help", "Help & Support")} /><Row icon="ⓘ" title="About Panditoo" onPress={() => open("about", "About Panditoo")} /><Row icon="▤" title="Terms & Conditions" onPress={() => open("terms", "Terms & Conditions")} /><Row icon="♢" title="Privacy Policy" onPress={() => open("privacy", "Privacy Policy")} /></Section><View style={[s.section, { marginTop: 8 }]}><Row icon="↪" title="Sign Out" onPress={logout} /><Row icon="▢" title="Delete Account" subtitle="Permanently remove your account" onPress={deleteAccount} danger /></View></ScrollView>;
}

const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#FAF7F2" }, center: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#FAF7F2" }, header: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 18 }, heading: { color: "#2D2824", fontSize: 24, fontWeight: "800" }, headingHindi: { color: "#92887F", fontSize: 11, marginTop: 4 }, bell: { width: 36, height: 36, borderWidth: 1, borderColor: "#E8DDD2", borderRadius: 12, alignItems: "center", justifyContent: "center" }, bellText: { color: "#554D47", fontSize: 18 }, profileCard: { margin: 17, padding: 16, borderRadius: 15, borderWidth: 1, borderColor: "#E8DCD1", backgroundColor: "#FFFDFC", flexDirection: "row", alignItems: "center" }, avatar: { width: 54, height: 54, borderRadius: 27, backgroundColor: "#F7DEDB", borderWidth: 1, borderColor: "#DCAAA6", alignItems: "center", justifyContent: "center" }, avatarText: { color: "#913B3B", fontSize: 25 }, editDot: { position: "absolute", right: -2, bottom: -2, width: 18, height: 18, borderRadius: 9, backgroundColor: "#913B3B", alignItems: "center", justifyContent: "center" }, editText: { color: "white", fontSize: 10 }, profileCopy: { flex: 1, marginLeft: 14 }, name: { color: "#342E2A", fontSize: 15, fontWeight: "800" }, profileMeta: { color: "#91877E", fontSize: 10, marginTop: 4 }, verified: { color: "#27845D", backgroundColor: "#E9F7EF", padding: 8, borderRadius: 8, fontSize: 9, overflow: "hidden" }, stats: { flexDirection: "row", marginHorizontal: 17, gap: 10, marginBottom: 16 }, stat: { flex: 1, height: 73, borderRadius: 11, borderWidth: 1, borderColor: "#E8DCD1", backgroundColor: "#FFFDFC", alignItems: "center", justifyContent: "center" }, statNumber: { color: "#913B3B", fontSize: 20, fontWeight: "700" }, statLabel: { color: "#877D74", fontSize: 10, marginTop: 6 }, sectionTitle: { color: "#857B72", fontSize: 10, fontWeight: "700", marginHorizontal: 17, marginTop: 10, marginBottom: 7 }, section: { marginHorizontal: 17, borderRadius: 14, borderWidth: 1, borderColor: "#E8DCD1", backgroundColor: "#FFFDFC", overflow: "hidden", marginBottom: 3 }, row: { minHeight: 62, flexDirection: "row", alignItems: "center", paddingHorizontal: 15, borderBottomWidth: 1, borderBottomColor: "#EEE5DC" }, rowIcon: { width: 34, height: 34, borderRadius: 10, backgroundColor: "#F6F1E9", alignItems: "center", justifyContent: "center" }, dangerIcon: { backgroundColor: "#FDEEEE" }, iconText: { color: "#9B7042", fontSize: 16 }, rowCopy: { flex: 1, marginLeft: 12 }, rowTitle: { color: "#5B524B", fontSize: 12 }, rowSubtitle: { color: "#A0968D", fontSize: 9, marginTop: 4 }, chevron: { color: "#91877E", fontSize: 20 }, rightText: { color: "#91877E", fontSize: 10 }, danger: { color: "#D24A4A" } });
