export const POLICY_VERSION = "2026-08-07";

// RELEASE BLOCKER: replace these values with the operating entity's verified details.
export const LEGAL_CONTACT = {
  operator: "Panditoo",
  address: "Operator registered address to be published before release",
  supportEmail: "support@panditoo.com",
  privacyEmail: "privacy@panditoo.com",
  grievanceOfficer: "Grievance Officer name to be published before release",
  grievanceEmail: "grievance@panditoo.com",
  jurisdiction: "the courts having jurisdiction under applicable Indian law",
};

const commonPrivacy = [
  ["Who we are", `Panditoo is operated by ${LEGAL_CONTACT.operator} (${LEGAL_CONTACT.address}). This policy applies to the Panditoo customer and partner apps, websites, support and marketplace services.`],
  ["Information we collect", "We collect account and contact details; booking, address and ceremony details; provider qualifications, identity proof, availability and service area; payment, refund, bank payout, earnings and withdrawal records; ratings, support messages and referral details. When a feature requires it, we may collect precise or approximate foreground location, a photo you select or capture, notification tokens, device/app information, IP address, authentication and security logs, and usage records."],
  ["Why we use it", "We use data to create and secure accounts; verify providers; match and fulfil bookings; calculate prices; process payments, refunds, credits and payouts; deliver OTPs and transactional notices; prevent fraud and safety incidents; provide support and resolve disputes; comply with law; and improve the service. Promotional messages are sent only where permitted and may be opted out of."],
  ["Permissions", "Location, camera, photos and notifications are requested only for the relevant feature. You can deny or revoke them in device settings. Denial may disable that feature but will not prevent unrelated use. A manually entered address may be used where available."],
  ["How information is shared", "We share only information reasonably necessary to evaluate and perform a booking between customers and eligible or confirmed providers. We also use contracted hosting, database, SMS/OTP, notification, payment (including Razorpay), banking/payout, storage, security, analytics and support providers. We may disclose data when lawfully required, to protect people or the service, or during a corporate transaction subject to safeguards. We do not sell personal data."],
  ["Payments", "The payment provider shown at checkout processes card, UPI or other payment credentials under its own policy. Panditoo receives transaction references, status, amount and limited payer information needed for reconciliation, refunds and fraud prevention."],
  ["Retention", "We keep data only as long as reasonably necessary for the stated purpose. OTPs expire quickly; operational copies and logs are removed under our retention schedule. Account data is retained while active. After deletion, data is deleted or de-identified unless a limited record must be retained for tax, accounting, payment, fraud, safety, dispute or other legal obligations. Booking and financial records are retained for the period required by Indian law."],
  ["Security and incidents", "We use reasonable administrative, technical and organisational safeguards, access controls and encrypted transport. No system is completely secure. Where applicable law requires it, affected users and authorities will be notified of a personal-data breach."],
  ["Your choices and rights", `You may request access to a summary of your data and processing, correction, completion, updating, erasure, consent withdrawal and grievance redressal by contacting ${LEGAL_CONTACT.privacyEmail}. Withdrawal is as easy as giving consent, does not affect earlier lawful processing, and may prevent features that require the data. We may verify your identity before acting. You may also nominate another person to exercise applicable rights in the event of death or incapacity. If an eligible grievance is not resolved through our process, you may complain to the Data Protection Board of India when the relevant provisions apply.`],
  ["Account deletion", "Use the account deletion control in the app where available or contact support. We will explain any narrow retention required for active bookings, refunds, chargebacks, withdrawals, disputes or law. Deleting an account does not cancel unpaid obligations or unresolved transactions."],
  ["Children", "The service is intended only for people aged 18 or older. We do not knowingly create accounts for children. Contact us if you believe a child has provided personal data."],
  ["International processing", "Service providers may process data in other locations. We use contractual and other safeguards required by applicable law and comply with any government restrictions on cross-border transfers."],
  ["Changes", "We may update this policy as the service or law changes. We will show the new effective date and seek fresh consent where a change requires it."],
  ["Contact and grievance", `Privacy: ${LEGAL_CONTACT.privacyEmail}\nSupport: ${LEGAL_CONTACT.supportEmail}\nGrievance Officer: ${LEGAL_CONTACT.grievanceOfficer}\nGrievance email: ${LEGAL_CONTACT.grievanceEmail}\nAddress: ${LEGAL_CONTACT.address}. We acknowledge complaints within 48 hours and aim to resolve consumer complaints within one month, subject to applicable law.`],
];

const commonTerms = [
  ["Eligibility and acceptance", "You must be at least 18, legally capable of contracting, and provide accurate information. By actively accepting these Terms and the Privacy Policy you enter a binding agreement with the operator. Keep control of your phone and promptly report suspected account misuse."],
  ["Marketplace role", "Panditoo provides technology that connects customers requesting in-person religious services with independent pandit providers. Providers are not employees or agents unless expressly stated. Verification is not a guarantee or endorsement, and a request, match, timing, outcome or uninterrupted service is not guaranteed."],
  ["Customer responsibilities", "Customers must provide accurate ceremony, date, time, participant and address details; disclose material requirements; provide a lawful, respectful and reasonably safe venue; and pay all charges displayed before confirmation. A person booking for another confirms authority to provide their details and instructions."],
  ["Provider responsibilities", "Providers must provide truthful identity, qualification, bank, tax, location, availability and service information; maintain required registrations; act professionally and safely; perform accepted bookings with reasonable skill and care; protect customer information; and use it only to fulfil the booking. Providers must not manipulate bookings, service OTPs, ratings, credits, prices or payments, or take users off-platform to evade disclosed fees."],
  ["Nature of religious services", "Religious practices, languages, traditions, duration and materials may vary by family, region and provider. Customers and providers must confirm material requirements before performance. The platform does not promise a spiritual, religious, personal, medical, legal or financial outcome, and information in the app is not professional advice."],
  ["Prices, payments and payouts", "The total price, components, taxes, payment timing and method are displayed before a customer confirms. Supported payments are processed by the provider shown at checkout. Provider earnings are subject to completed-service validation, disclosed platform fees, tax withholding, refunds, chargebacks and payout controls. Partner credits, if offered, are limited-purpose, non-transferable, have no cash value and are refundable only as displayed or required by law. The applicable payout estimate and withdrawal threshold are shown before a withdrawal request."],
  ["Cancellation, refunds and disputes", "The cancellation and refund rule shown before booking confirmation forms part of these Terms. A material price or rule change requires customer acceptance. Provider cancellation, no-show, unsafe conditions, force majeure, fraud and service-quality disputes may be reviewed individually. Contact support promptly with the booking reference and evidence. Nothing limits mandatory consumer rights."],
  ["Safety and prohibited conduct", "Do not use the service for unlawful, fraudulent, deceptive, abusive, discriminatory, dangerous or exploitative conduct; harassment; impersonation; unauthorised data collection; scraping; malware; account intrusion; or infringement of another person's rights. Panditoo is not an emergency service; contact local emergency services when needed."],
  ["Content and ratings", "You retain ownership of content you submit and grant the operator a non-exclusive, worldwide, royalty-free licence to host, process, reproduce and display it only as reasonably necessary to operate, protect and promote the service. You must have the right to submit it. Ratings must reflect genuine experiences. Unlawful or policy-violating content may be removed."],
  ["Intellectual property", "The apps, software, branding and platform content belong to the operator or licensors. You receive a limited, revocable, non-exclusive and non-transferable right to use the service for its intended purpose. You may not copy, reverse engineer or exploit it except where law permits."],
  ["Suspension and termination", "You may stop using the service and request deletion. We may restrict or terminate access for material breach, fraud, safety risk, legal requirement, repeated misconduct or non-payment. Where appropriate, notice and a reasonable appeal opportunity will be provided. Clauses intended to survive termination remain effective."],
  ["Disclaimers and liability", "To the extent permitted by law, the platform is provided on an as-available basis and the operator is not responsible for indirect or consequential loss that was not reasonably foreseeable. Nothing excludes fraud, wilful misconduct, liability that cannot legally be excluded, or statutory consumer rights. Each party remains responsible for its own acts and legal obligations."],
  ["Indemnity and force majeure", "To the extent permitted by law, a user responsible for an unlawful act, material breach or third-party rights violation must compensate the operator for resulting third-party claims and reasonable costs. No party is liable for delay caused by events beyond reasonable control, but payment, refund and consumer obligations continue where law requires."],
  ["Governing law", `Indian law governs these Terms. Disputes should first be raised with ${LEGAL_CONTACT.grievanceEmail}. Courts and consumer commissions with mandatory jurisdiction remain available; venue is ${LEGAL_CONTACT.jurisdiction}. Nothing requires a consumer to waive a forum or remedy provided by law.`],
  ["Changes and contact", `Material changes will be notified and fresh acceptance obtained where required. Support: ${LEGAL_CONTACT.supportEmail}. Grievance Officer: ${LEGAL_CONTACT.grievanceOfficer}, ${LEGAL_CONTACT.grievanceEmail}, ${LEGAL_CONTACT.address}.`],
];

export const LEGAL_DOCUMENTS = {
  privacy: { title: "Privacy Policy", effectiveDate: "7 August 2026", version: POLICY_VERSION, sections: commonPrivacy },
  terms: { title: "Terms & Conditions", effectiveDate: "7 August 2026", version: POLICY_VERSION, sections: commonTerms },
};
